version: "3"
services:
    app:
        restart: always
        container_name: docker-web
        build:
            context: ./
        ports:
            - "8000:80"
            - "63790:6379"
        volumes:
            - ./app:/var/www/html
            - ./conf.d/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf
            - ./conf.d/default.conf:/etc/nginx/conf.d/default.conf
            - ./conf.d/redis.conf:/etc/redis/redis.conf
        links:
            - db
    db:
        restart: always
        image: mysql:5.7
        container_name: docker-mysql
        environment:
            - "MYSQL_DATABASE=docker-mysql"
            - "MYSQL_USER=root"
            - "MYSQL_ROOT_PASSWORD=root"
        volumes:
            - ./stores/db:/var/lib/mysql
        ports:
            - "33060:3306"