version: "3"
services:
    app:
        restart: always
        container_name: docker-web
        build:
            context: ./
        ports:
            - "8000:80"
            - "5000:6379"
        volumes:
            - ./app:/var/www/html
            - ./conf.d/default.conf:/etc/nginx/conf.d/default.conf
            - ./conf.d/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf
            - ./conf.d/redis.conf:/etc/redis/redis.conf